version: "3.9"

x-image-common:
  &build-common
  build:
    context: .
    dockerfile: Dockerfile
  image: symbiose/take-home/zeke/gcp-function-runtime

x-dev-volumes:
  &dev-volumes
  - ./app:/root/app
  - ./test:/root/test

services:
  dev:
    <<: *build-common
    volumes: *dev-volumes
    command:
      - "functions-framework"
      - "--source"
      - "app/functions/http/send_email/__init__.py"
      - "--target"
      - "send_email"
      - "--debug"
    ports:
      - "8080:8080"
    env_file:
      - ./env/dev.env
    environment:
      - PYTHONPATH=.
      - PYTHONUNBUFFERED=1
